# Intentionally created to init a CNI
---
- name: provide software required by Calico
  apt:
    pkg:
      - ipip
      - ipset
      - iptables
    state: present

- name: install Calico as of https://docs.projectcalico.org/getting-started/kubernetes/installation/calico
  block:
  - name: download Calico manifest to edit it
    get_url:
      url: "https://docs.projectcalico.org/v{{ versions.calico }}/manifests/calico.yaml"
      dest: "/var/tmp/calico.yaml"
    register: calico_fetched
  - name: edit Calico manifest to change the required network cidr
    replace:
      path: /var/tmp/calico.yaml
      regexp: "192.168.0.0\/16"
      replace: "{{ kubeadm.pod_network_cidr }}"
    when:
      - calico_fetched is defined
      - calico_fetched.changed  
  - name: create the Calico resources to manage routes and complete Pod-to-Pod networking
    shell: kubectl apply -f /var/tmp/calico.yaml
    args:
      creates: "{{ marker.cni_applied }}"
    notify: mark cni applied
  # https://github.com/kubernetes-sigs/kind/issues/891
  # https://alexbrand.dev/post/creating-a-kind-cluster-with-calico-networking/
  - name: disable RPF (reverse path filtering) to avoid Calico nodes fail on Ubuntu
    shell: kubectl -n kube-system set env daemonset/calico-node FELIX_IGNORELOOSERPF=true
    args:
      creates: "{{ marker.rpf_disabled }}"
    notify: mark rpf disabled