# Intentionally created to init a CNI
---
- name: verify connectivity to gcr.io registries to init kubeadm
  shell: kubeadm config images pull
  args:
    creates: "{{ marker.cni_applied }}"

- block:
  - name: download Calico manifests to provide CNI
    get_url:
      url: "{{ item.url }}"
      dest: "/var/tmp/{{ item.name }}.yaml"
    register: calico_fetched
    loop:
      - { name: calico, url: "https://docs.projectcalico.org/v{{ versions.calico }}/manifests/calico.yaml" }
      - { name: calico_rbac, url: "https://docs.projectcalico.org/v{{ versions.calico_rback }}/getting-started/kubernetes/installation/hosted/rbac-kdd.yaml" }
  - name: edit calico manifest to change the required network cidr
    replace:
      path: /var/tmp/calico.yaml
      regexp: "192.168.0.0\/16"
      replace: "{{ kubeadm.pod_network_cidr }}"
    when:
      - calico_fetched is defined
      - calico_fetched.changed  

- name: create the Calico resources to manage routes and complete Pod-to-Pod networking
  shell: kubectl apply -f {{ item }}
  args:
    creates: "{{ marker.cni_applied }}"
  notify: mark cni applied
  loop:
    - /var/tmp/calico.yaml
    - /var/tmp/calico_rbac.yaml
