# Intentionally created to have a place for variables
---
api:
  host: pi10.dmz.local
  port: 6443

# Some helper to stay idempotent
marker:
  cluster_joined: /marker-cluster-joined
  docker_inited: /marker-docker-inited
  cni_applied: /marker-cni-applied
  kubeadm_holded: /marker-kubeadm-holded
  kubeadm_inited: /marker-kubeadm-inited
  password_changed: /marker-password-changed
  rpf_disabled: /marker-rpf-disabled
  swap_disabled: /marker-swap-disabled

# https://docs.projectcalico.org/v3.12/getting-started/kubernetes/installation/calico
versions:
  docker: "18.09.9~3-0"
  containerd: "1.2.6-3"
  k8s: 1.16.6
  calico: 3.12

kubeadm:
  pod_network_cidr: '10.244.0.0/16'
