# Intentionally created to have a place for variables
---
api:
  host: pi10.dmz.local
  port: 6443

# Some helpers to stay idempotent
marker:
  cluster_joined: /marker-cluster-joined
  docker_inited: /marker-docker-inited
  cni_applied: /marker-cni-applied
  kubeadm_holded: /marker-kubeadm-holded
  kubeadm_inited: /marker-kubeadm-inited
  metallb_secret_added: /marker-metallb-secret-added
  password_changed: /marker-password-changed
  rpf_disabled: /marker-rpf-disabled
  swap_disabled: /marker-swap-disabled

versions:
  docker: "5:19.03.11~"
  containerd: "1.2.13-2"
  k8s: 1.18.4
  calico: 3.14.1
  metallb: 0.9.3

lb:
  # This must match a range the the router knows about but does not use for DHCP.
  addresses:
    begin: 192.168.220.100
    end: 192.168.220.200

kubeadm:
  pod_network_cidr: '10.244.0.0/16'
