# Intentionally created to have a place for variables
---
api:
  host: pi10.dmz.local
  port: 6443

# Some helper to stay idempotent
marker:
  cluster_joined: /marker-cluster-joined
  docker_inited: /marker-docker-inited
  cni_applied: /marker-cni-applied
  kubeadm_holded: /marker-kubeadm-holded
  kubeadm_inited: /marker-kubeadm-inited
  password_changed: /marker-password-changed
  swap_disabled: /marker-swap-disabled

versions:
  docker: 18.09
  k8s: 1.16.1
  calico: 3.9
  calico_rback: 3.3

kubeadm:
  pod_network_cidr: '10.244.0.0/16'
