# Intentionally created to avoid CNI applied is run more than once
---
- name: mark cni applied
  file:
    path: "{{ marker.cni_applied }}"
    state: touch

- name: mark rpf disabled
  file:
    path: "{{ marker.rpf_disabled }}"
    state: touch