# Intentionally created to avoid password change runs more than once
---
- name: mark password changed
  file:
    path: "{{ marker.password_changed }}"
    state: touch

- name: mark docker inited
  file:
    path: "{{ marker.docker_inited }}"
    state: touch

- name: restart docker
  service:
    name: docker
    state: restarted
