# Intentionally added to upgrade OS.
---
- name: update OS packages and handle dependency changes to stay up-to-date
  apt:
    upgrade: dist
    force_apt_get: yes
    update_cache: yes

- name: enable ipv4 forward to route packages as required for Kubernetes Service delivery 
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes

# https://wiki.debian.org/Suspend
- name: disable suspend and hibernation to avoid box not reachable
  systemd:
    masked: yes
    name: "{{ item }}"
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target

# Sets an unkown password since the 'pi' user has paswordless sudo access and SSH pub key connection is in place.
- name: randomize default password to ensure security
  shell: /usr/sbin/chpasswd
  args:
    stdin: "pi:{{ 'passwordsaresecret'|password_hash('sha512') }}"
    creates: "{{ marker.password_changed }}"
  notify: mark password changed

- name: disable bluetooth and wifi to save energy and avoid radiation
  lineinfile:
    path: /boot/config.txt
    regexp: "{{ item }}"
    line: "{{ item }}"
  loop:
    - dtoverlay=disable-wifi
    - dtoverlay=disable-bt
  register: bootconfig

- name: disable the service that initializes the modem so it doesn't use the UART
  systemd:
    name: hciuart
    enabled: no

- name: reboot to apply bootconfig changes
  reboot:
  when:
    - bootconfig is defined
    - bootconfig.changed