# Intentionally created to install docker in a specific version.
---
- name: up/downgrade Docker to add the required version
  block:
  - name: remove holds to unfix Docker version
    shell: apt-mark unhold docker.io
  - name: installing Docker "{{ versions.docker }}"
    apt:
      autoremove: yes
      # allow downgrade if neccessary
      force: true
      force_apt_get: yes
      name:
        - "docker.io={{ versions.docker }}*"
  - name: setting hold to fix Docker version to avoid an unwanted upgrade
    shell: apt-mark hold docker.io
  - name: start and enable Docker to start on boot
    service:
      enabled: yes
      state: started
      name: docker
  - name: placing Docker daemon configuration file
    copy:
      dest: /etc/docker/daemon.json
      src: daemon.json
    notify: restart docker
