---
- block:
  - name: disable bluetooth and wifi to save energy and avoid radiation
    lineinfile:
      path: /boot/firmware/config.txt
      regexp: "{{ item }}"
      line: "{{ item }}"
      create: yes
    loop:
      - dtoverlay=disable-wifi
      - dtoverlay=disable-bt
    register: bootconfig

  - name: reboot to apply bootconfig changes
    reboot:
    when:
      - bootconfig is defined
      - bootconfig.changed

- block:
  - name: append pattern to enable cgroup memory as required by kubeadm
    lineinfile:
      path: /boot/firmware/nobtcmd.txt
      regexp: "^(.*fixrtc)$"
      line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
      backrefs: yes
    register: cgroup_edited
  - name: reboot to apply bootconfig changes
    reboot:
    when:
      - cgroup_edited is defined
      - cgroup_edited.changed

- name: fix systemd issue preventing generating MAC https://github.com/systemd/systemd/issues/3374#issuecomment-288882355
  block:
  - name: provide default network settings
    copy:
      src: 99-default.link
      dest: /etc/systemd/network/99-default.link
    register: systemd_network
  - name: reload daemon to apply changes
    service:
      daemon_reload: yes
    when:
      - systemd_network is defined
      - systemd_network.changed
