---
- block:
  - name: disable bluetooth and wifi to save energy and avoid radiation
    lineinfile:
      path: /boot/firmware/config.txt
      regexp: "{{ item }}"
      line: "{{ item }}"
      create: yes
    loop:
      - dtoverlay=disable-wifi
      - dtoverlay=disable-bt
    register: bootconfig

  - name: reboot to apply bootconfig changes
    reboot:
    when:
      - bootconfig is defined
      - bootconfig.changed

- block:
  - name: append pattern to enable cgroup memory as required by kubeadm
    lineinfile:
      path: /boot/firmware/nobtcmd.txt
      regexp: "^(.*)$"
      line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1'
      backrefs: yes
    register: cgroup_edited    
  - name: reboot to apply bootconfig changes
    reboot:
    when:
      - cgroup_edited is defined
      - cgroup_edited.changed

# muss man in die calico.yaml noch eintragen: cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1
# ???