# Intentionally created to bake Raspberry Pi
---
- include: boot.yaml

- name: render current depoyment to display at login
  shell: >
    echo "Last Ansible deployment: $(date)" > /etc/motd

- block:
  - name: upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
    register: upgrades
  - name: update OS packages and handle dependency changes to stay up-to-date
    apt:
      upgrade: dist
      force_apt_get: yes
      update_cache: yes
    register: updates
  - name: reboot to apply os changes
    reboot:
    when: (upgrades is defined and upgrades.changed) or (updates is defined and updates.changed)

# https://wiki.debian.org/Suspend
- name: disable suspend and hibernation to avoid box not reachable
  systemd:
    masked: yes
    name: "{{ item }}"
  loop:
    - sleep.target
    - suspend.target
    - hibernate.target
    - hybrid-sleep.target

- name: avoid ssh brute force attacks by disabling password login
  replace:
    path: /etc/ssh/sshd_config
    regexp: '^#   PasswordAuthentication yes$'
    replace: 'PasswordAuthentication no'
  notify: restart ssh

# Docker will take care of ipv4 forwarding!
- include: docker.yaml