# Intentionally created to let worker join cluster
---
- name: let worker join to extend the cluster
  shell: kubeadm join --token={{ k8s_token }} --discovery-token-unsafe-skip-ca-verification {{ api.host }}:{{ api.port }}
  args:
    creates: "{{ marker.cluster_joined }}"
  notify: mark cluster joined